apiVersion: 1

datasources:
  - name: AlertManager
    type: alertmanager
    uid: alertmanager
    url: http://alertmanager:9093
    access: proxy
    jsonData:
      implementation: prometheus
    isDefault: false